version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=library_management_service
      - POSTGRES_PASSWORD=71br4r1@n
      - POSTGRES_DB=library
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local